import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<h1> Wow! Next js project running </h1>

				<hr />
				<nav>
					<ul className="flex gap-3">
						<li>
							<a href="/dashboard">Dashboard</a>
						</li>
						<li>
							<a href="/about">About</a>
						</li>
						<li>
							<a href="/service">Service</a>
						</li>
						<li>
							<a href="/users">Users</a>
						</li>
						<li>
							<a href="/account">Account</a>
						</li>
					</ul>
				</nav>

				<hr />

				<main>{children}</main>
			</body>
		</html>
	);
}
